# Generated by Django 2.1.5 on 2019-05-31 11:09

import ckeditor_uploader.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mainapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('url_code', models.CharField(blank=True, default='НЕ УКАЗАН', max_length=30, verbose_name='Код ссылки')),
                ('short_description', models.CharField(blank=True, max_length=200, verbose_name='Краткое описание')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст')),
                ('publish_on_main_page', models.BooleanField(default=False, verbose_name='Опубликовать на главной')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'get_latest_by': ['created_date'],
                'verbose_name': 'Статья',
                'ordering': ['created_date'],
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='Attestat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Название аттестата(сертификата)')),
                ('image', models.ImageField(upload_to='upload/', verbose_name='Скан аттестата')),
                ('number', models.SmallIntegerField(verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Аттестат соответствия',
                'verbose_name_plural': 'Аттестаты соответствия',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.CreateModel(
            name='ChlenKomissii',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100, verbose_name='ФИО Члена комиссии')),
                ('udost_type', models.CharField(choices=[('Персонал', 'Персонал'), ('Материалы', 'Материалы'), ('Оборудование', 'Оборудование'), ('Технологии', 'Технологии'), ('Оценка квалификации', 'Оценка квалификации')], default='Персонал', max_length=20, verbose_name='Тип удостоверения')),
                ('udost_number', models.CharField(max_length=20, verbose_name='Номер удостоверения')),
                ('udost_gtu', models.CharField(max_length=100, verbose_name='Область распространения (ГТУ)')),
                ('udost_sp_sv', models.CharField(max_length=200, verbose_name='Область аттестации(способы сварки, материалы и т.д.)')),
            ],
            options={
                'verbose_name': 'Член комиссии',
                'verbose_name_plural': 'Члены комиссии',
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название вставки')),
                ('code', models.CharField(default='КОД_ВСТАВКИ', max_length=64, verbose_name='Уникальный код вставки')),
                ('html', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Форматирование вставки')),
            ],
            options={
                'verbose_name': 'Вставка',
                'verbose_name_plural': 'Вставки',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название контакта')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('email', models.EmailField(max_length=64, verbose_name='Адрес электронной почты')),
                ('phone', models.CharField(max_length=64, verbose_name='Телефон')),
                ('number', models.SmallIntegerField(default=0, verbose_name='Порядок вывода на сайт')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('url_code', models.CharField(blank=True, default='НЕ УКАЗАН', max_length=30, verbose_name='Код ссылки')),
                ('document', models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'doc', 'jpg', 'jpeg'], message='Неправильный тип файла, используйте                                        PDF, DOCX, DOC, JPG, JPEG')], verbose_name='Документ')),
                ('number', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Порядок сортировки')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Загружен')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('publish_on_main_page', models.BooleanField(default=False, verbose_name='Опубиковать на главной')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название категории')),
                ('number', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Категория документа',
                'verbose_name_plural': 'Категории документов',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_code', models.CharField(max_length=30, verbose_name='Код ссылки')),
                ('title', models.CharField(max_length=60, verbose_name='Заголовок ссылки')),
                ('url', models.CharField(default='НЕТ', max_length=200, verbose_name='Адрес ссылки')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, verbose_name='Заголовок')),
                ('typeof', models.CharField(blank=True, max_length=64, verbose_name='Тип сообщения')),
                ('params', models.CharField(blank=True, max_length=512, verbose_name='Параметры сообщения')),
                ('sender_email', models.EmailField(blank=True, max_length=64, verbose_name='Адрес электронной почты')),
                ('sender_phone', models.CharField(blank=True, max_length=64, verbose_name='Телефон')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата получения')),
                ('status', models.IntegerField(choices=[(0, 'new'), (1, 'registered'), (2, 'added_to_sending_queue'), (3, 'notify_sent')], default=0, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('url_code', models.CharField(blank=True, default='НЕ УКАЗАН', max_length=30, verbose_name='Код ссылки')),
                ('short_description', models.CharField(blank=True, max_length=200, verbose_name='Краткое описание')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст')),
                ('publish_on_main_page', models.BooleanField(default=False, verbose_name='Опубликовать на главной')),
                ('publish_on_news_page', models.BooleanField(default=False, verbose_name='Опубликовать в ленте новостей')),
                ('secondery_main', models.BooleanField(default=False, verbose_name='Опубликовать на главной как новость без картинки')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category', verbose_name='Категория')),
            ],
            options={
                'get_latest_by': ['created_date'],
                'verbose_name': 'Страница',
                'ordering': ['created_date'],
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='PostPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload/', verbose_name='изображение')),
                ('title', models.CharField(blank=True, default=mainapp.models.get_image_filename, max_length=64, verbose_name='название')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Позиция')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='mainapp.Post', verbose_name='новость')),
            ],
            options={
                'verbose_name': 'Фото',
                'ordering': ['position'],
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_logotype', models.ImageField(blank=True, default=None, null=True, upload_to='upload/', verbose_name='Логотип организации')),
                ('org_short_name', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Краткое название организации')),
                ('org_full_name', models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Полное название организации')),
                ('org_intro', models.TextField(blank=True, default=None, null=True, verbose_name='Текст для главной страницы')),
                ('org_main_phone', models.CharField(blank=True, default=None, max_length=40, null=True, verbose_name='Главный телефон организации (используется в хедере)')),
                ('org_main_phone_text', models.CharField(blank=True, default=None, max_length=40, null=True, verbose_name='Подпись под телефоном в хедере, например "Многоканальный"')),
                ('org_secondary_phone', models.CharField(blank=True, default=None, max_length=40, null=True, verbose_name='Второй телефон организации (используется в хедере)')),
                ('org_secondary_phone_text', models.CharField(blank=True, default=None, max_length=40, null=True, verbose_name='Подпись под вторым телефоном в хедере, например "Бухгалтерия"')),
                ('org_phones', models.TextField(blank=True, default=None, null=True, verbose_name='Телефоны')),
                ('org_email', models.TextField(blank=True, default=None, null=True, verbose_name='Адрес электронной почты')),
                ('org_header_emails', models.TextField(blank=True, default=None, null=True, verbose_name='Адреса электронной почты (для хедера)')),
                ('org_header_phones', models.TextField(blank=True, default=None, null=True, verbose_name='Телефоны (для хедера)')),
                ('org_address', models.TextField(blank=True, default=None, null=True, verbose_name='Адрес местоположения организации')),
                ('org_address_map_link', models.URLField(blank=True, default=None, null=True, verbose_name='Ссылка на карту')),
                ('org_csp_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='шифр ЦСП (необязательно)')),
                ('org_csp_reestr_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на реестр ЦСП')),
                ('org_acsp_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='шифр АЦСП (необязательно)')),
                ('org_acsp_reestr_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на реестр АЦСП')),
                ('org_acsm_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='шифр АЦСМ (необязательно)')),
                ('org_acsm_reestr_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на реестр АЦСМ')),
                ('org_acso_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='шифр АЦСО (необязательно)')),
                ('org_acso_reestr_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на реестр АЦСО')),
                ('org_acst_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='шифр АЦСТ (необязательно)')),
                ('org_acst_reestr_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на реестр АЦСТ')),
                ('org_cok_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='шифр ЦОК (необязательно)')),
                ('org_cok_reestr_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на реестр ЦОК')),
                ('number', models.SmallIntegerField(blank=True, null=True, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Профиль организации',
                'verbose_name_plural': 'Профили организации',
            },
        ),
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, verbose_name='Название')),
                ('org', models.CharField(blank=True, max_length=120, verbose_name='Организация')),
                ('typeof', models.CharField(blank=True, max_length=64, verbose_name='Тип')),
                ('params', models.CharField(blank=True, max_length=999, verbose_name='Параметры')),
                ('created_date', models.DateField(blank=True, verbose_name='Дата получения')),
                ('status', models.IntegerField(choices=[(0, 'new'), (1, 'published')], default=0, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Запись реестра',
                'verbose_name_plural': 'Записи реестра',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='\n            При добавлении услуги в этот раздел автоматически\n            будет создан пункт меню в разделе "Услуги", в котором они\n            сортируются в соответствии с порядком сортировки\n        ', max_length=64, verbose_name='Название услуги')),
                ('short_description', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Краткое описание услуги')),
                ('html', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание услуги')),
                ('number', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Порядок сортировки')),
                ('bg_photo', models.ImageField(blank=True, default=None, null=True, upload_to='upload/', verbose_name='Картинка для главной')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='Фотография')),
                ('name', models.CharField(max_length=120, verbose_name='ФИО')),
                ('job', models.CharField(max_length=120, verbose_name='Должность')),
                ('experience', models.CharField(blank=True, max_length=500, verbose_name='Опыт работы')),
                ('priority', models.SmallIntegerField(default=0, verbose_name='Приоритет')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='mainapp.Tag', verbose_name='Тэги'),
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.DocumentCategory'),
        ),
        migrations.AddField(
            model_name='document',
            name='post',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Post', verbose_name='Страница'),
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(blank=True, to='mainapp.Tag', verbose_name='Тэги'),
        ),
        migrations.AddField(
            model_name='chlenkomissii',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Tag'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='mainapp.Tag', verbose_name='Тэги'),
        ),
    ]
