# Generated by Django 2.1.5 on 2019-06-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderservice',
            name='compound',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Состав заявки'),
        ),
    ]
