# Generated by Django 2.1.5 on 2019-05-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_sidepanel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profstandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название профстандарта')),
                ('info', models.CharField(max_length=300, verbose_name='Информация о стандарте(код)')),
                ('reg_number', models.CharField(max_length=20, verbose_name='Регистрационный номер')),
                ('mintrud_prikaz', models.CharField(max_length=100, verbose_name='Приказ минтруда')),
                ('document', models.FileField(upload_to='upload/', verbose_name='Файл')),
                ('number', models.SmallIntegerField(verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Профстандарт',
                'verbose_name_plural': 'Профстандарты',
            },
        ),
    ]
