# Generated by Django 2.1.5 on 2019-06-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_profstandard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя контакта')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон контакта')),
                ('ready', models.BooleanField(blank=True, default=False, null=True, verbose_name='Вопрос решен')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
