# Generated by Django 2.1.5 on 2019-05-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_auto_20190516_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='org_secondary_phone_text',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Подпись под вторым телефоном в хедере, например "Бухгалтерия"'),
        ),
    ]
